//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Message
    {
        public int reportID { get; set; }
        public string userIDNum { get; set; }
        public string messageReport { get; set; }
        public Nullable<System.DateTime> dateReport { get; set; }
        public string reportStatus { get; set; }
    }
}
