//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllReports
    {
        public int itemID { get; set; }
        public string username { get; set; }
        public string itemName { get; set; }
        public string itemType { get; set; }
        public string itemStatus { get; set; }
        public string itemDescription { get; set; }
        public string ImageUrl { get; set; }
        public string locationName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string reportStatus { get; set; }
        public string returnMethod { get; set; }
        public Nullable<int> reportID { get; set; }
        public string userIDNum { get; set; }
        public string messageNotif { get; set; }
        public Nullable<System.DateTime> dateReceive { get; set; }
    }
}
